openapi: 3.0.3
info:
  title: API UX - GESTION DE COMPRAS
  description: |-
    API de Gestion de compras del 
    Grupo Regaeton, Wisin y Yandel (API UX)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:4000/ux-productos/servicio-al-cliente/v1
tags:
  - name: Compra
    description: Operaciones sobre la compra (API UX)
    externalDocs:
      description: Encuentra mas
      url: http://swagger.io
paths:
  /mostrar-compras:
    get:
      tags:
        - Compra
      summary: Mostrar compras (API UX)
      description: Obtiene la lista de compras disponibles
      operationId: getCompras
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Compra'
        '405':
          description: Entrada inválida

components:
  schemas:
    Compra:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        productoId:
          type: integer
          format: int64
          example: 198772
        cantidad:
          type: integer
          format: int32
          example: 7
        fechaCompra:
          type: string
          format: date-time
        estado:
          type: string
          description: Estado de la compra
          example: aprobado
          enum:
            - reservado
            - aprobado
            - entregado
        completado:
          type: boolean
      xml:
        name: compra
